### ISSUE TITLE
Add pin_code parameter on VerifyRequest

### ISSUE THREAD

**Issue by lshep311** [nexmo-community/nexmo-go#22]
We leverage the pin_code parameter on our requests to the Verify API. We would like to have this parameter added so we can adopt using this client moving forward.

**Comment by lornajane** [comment]
I'm sorry but the pin code field isn't a mainstream feature and isn't available to all users so we're not adding support for it to our libraries at this time. Please do keep the requests coming though, we're actively working on this library and it is useful to get input.
